//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceLibros
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autor_Producto
    {
        public int AutorID { get; set; }
        public int producto_id { get; set; }
        public Nullable<System.DateTime> FechaAsociacion { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual productos productos { get; set; }
    }
}
