//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceLibros
{
    using System;
    using System.Collections.Generic;
    
    public partial class envios
    {
        public int envio_id { get; set; }
        public Nullable<int> pedido_id { get; set; }
        public string direccion_envio { get; set; }
        public string ciudad { get; set; }
        public string codigo_postal { get; set; }
        public string pais { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<System.DateTime> fecha_entrega_estimada { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public string estado { get; set; }
    
        public virtual pedidos pedidos { get; set; }
    }
}
