//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceLibros
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECommercelibrosEntities : DbContext
    {
        public ECommercelibrosEntities()
            : base("name=ECommercelibrosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<Autor_Producto> Autor_Producto { get; set; }
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<envios> envios { get; set; }
        public virtual DbSet<Imagen_Producto> Imagen_Producto { get; set; }
        public virtual DbSet<metodos_pago> metodos_pago { get; set; }
        public virtual DbSet<pedido_productos> pedido_productos { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
        public virtual DbSet<producto_categorias> producto_categorias { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<transacciones> transacciones { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
