//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceLibros
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_categorias
    {
        public int producto_id { get; set; }
        public int categoria_id { get; set; }
        public string pcDescripcion { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual productos productos { get; set; }
    }
}
