//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceLibros
{
    using System;
    using System.Collections.Generic;
    
    public partial class transacciones
    {
        public int transaccion_id { get; set; }
        public Nullable<int> pedido_id { get; set; }
        public Nullable<int> metodo_pago_id { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public decimal monto { get; set; }
        public string estado { get; set; }
    
        public virtual metodos_pago metodos_pago { get; set; }
        public virtual pedidos pedidos { get; set; }
    }
}
