//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceLibros.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.TC1Soap")]
    public interface TC1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarTarjeta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VerificarTarjeta(string numeroTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarTarjeta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> VerificarTarjetaAsync(string numeroTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pagar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Pagar(string numeroTarjeta, decimal monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pagar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PagarAsync(string numeroTarjeta, decimal monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarTarjeta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AgregarTarjeta(string numeroTarjeta, string cvv, System.DateTime fechaExpiracion, string tipoTarjeta, string empresa, decimal saldo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarTarjeta", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AgregarTarjetaAsync(string numeroTarjeta, string cvv, System.DateTime fechaExpiracion, string tipoTarjeta, string empresa, decimal saldo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TC1SoapChannel : EcommerceLibros.ServiceReference1.TC1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TC1SoapClient : System.ServiceModel.ClientBase<EcommerceLibros.ServiceReference1.TC1Soap>, EcommerceLibros.ServiceReference1.TC1Soap {
        
        public TC1SoapClient() {
        }
        
        public TC1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TC1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TC1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TC1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet VerificarTarjeta(string numeroTarjeta) {
            return base.Channel.VerificarTarjeta(numeroTarjeta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> VerificarTarjetaAsync(string numeroTarjeta) {
            return base.Channel.VerificarTarjetaAsync(numeroTarjeta);
        }
        
        public string Pagar(string numeroTarjeta, decimal monto) {
            return base.Channel.Pagar(numeroTarjeta, monto);
        }
        
        public System.Threading.Tasks.Task<string> PagarAsync(string numeroTarjeta, decimal monto) {
            return base.Channel.PagarAsync(numeroTarjeta, monto);
        }
        
        public string AgregarTarjeta(string numeroTarjeta, string cvv, System.DateTime fechaExpiracion, string tipoTarjeta, string empresa, decimal saldo) {
            return base.Channel.AgregarTarjeta(numeroTarjeta, cvv, fechaExpiracion, tipoTarjeta, empresa, saldo);
        }
        
        public System.Threading.Tasks.Task<string> AgregarTarjetaAsync(string numeroTarjeta, string cvv, System.DateTime fechaExpiracion, string tipoTarjeta, string empresa, decimal saldo) {
            return base.Channel.AgregarTarjetaAsync(numeroTarjeta, cvv, fechaExpiracion, tipoTarjeta, empresa, saldo);
        }
    }
}
